<?php

/**
 * Implementation of hook_menu().
 */
function paypal_billing_admin_menu() {
  $items = array();

  // List plans.
  $items['admin/commerce/paypal-plans'] = array(
    'title' => 'PayPal Plans',
    'page callback' => 'paypal_plans_overview_page',
    'access arguments' => array('administer paypal billing plan'),
  );

  // Add a new plan.
  $items['admin/commerce/paypal-plans/add'] = array(
    'title' => 'Add plan',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('paypal_billing_admin_add_plan'),
    'access arguments' => array('administer paypal billing plan'),
    'type' => MENU_LOCAL_ACTION,
  );

  /////////////////////////////

  $items['create-plan'] = array(
    'title' => '1: Created billing example plan',
    'page callback' => 'sample_create_plan',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['get-plan/%'] = array(
    'title' => '2: Example created billing plan details',
    'page callback' => 'sample_get_plan',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['activate-plan/%'] = array(
    'title' => '3: Plan activated',
    'page callback' => 'sample_activate_plan',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );


  $items['list-plans'] = array(
    'title' => '4: List all created plans',
    'page callback' => 'sample_list_plans',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * List all available plans.
 * menu callback.
 * @todo implement.
 * @var $plan \PayPal\Api\Plan
 */
function paypal_plans_overview_page() {
  _paypal_get_sdk();
  $PlanList = paypal_sdk_get_billing_plans();
  $plans = $PlanList->getPlans();

  $out = '';
  /** @var \PayPal\Api\Plan $plan */
  foreach ($plans as $plan) {
    $out .= $plan->getId() . "<br>" .
      $plan->getName() . "<br>" .
      $plan->getDescription() . "<br>" .
      $plan->getState() . "<br>" .
      $plan->getCreateTime() . "<br>" .
      $plan->getUpdateTime() . "<br><br>";
  }

  return $out;
  // Todo implement a "tableselect" and bulk for CRUD

}

function paypal_billing_admin_add_plan($form, &$form_state) {

  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#required' => TRUE,
  );

  $form['description'] = array(
    '#type' => 'textfield',
    '#title' => t('Description'),
    '#required' => TRUE,
  );

  $form['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Value'),
    '#required' => TRUE,
  );

  $form['currency'] = array(
    '#type' => 'textfield',
    '#title' => t('Currency'),
    '#required' => TRUE,
  );


  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Add plan'),
  );

  return $form;
}

/**
 * @return string
 */
function sample_create_plan() {
  if (_paypal_get_sdk()) {

    $plan = paypal_sdk_create_plan(array(
      'name' => 'Cuota anual aed',
      'description' => 'Descripcion de la cuota',
      'type' => 'fixed'
    ));

    $currency = paypal_sdk_create_currency(array(
      'value' => 100,
      'currency' => 'USD',
    ));

    $paymentDefinition = paypal_sdk_create_payment_definition(array(
      'name' => 'Regular Payments',
      'type' => 'REGULAR',
      'frecuency' => 'Month',
      'frecuency-interval' => '2',
      'cycles' => '12',
      'currency' => $currency,
    ));

    $chargeModel = paypal_sdk_create_charge_model(array(
      'type' => 'SHIPPING',
      'currency' => $currency,
    ));

    $merchantPreferences = paypal_sdk_create_merchant_preferences(array(
      'return-url' => "http://aed.local/ExecuteAgreement.php?success=true",
      'cancel-url' => "http://aed.local/ExecuteAgreement.php?success=false",
      'auto-bill' => 'yes',
      'initial-fail-amount-action' => 'CONTINUE',
      'max-fail-attemps' => '0',
      'currency' => $currency,
    ));

    $paymentDefinition->setChargeModels(array($chargeModel));
    $plan->setPaymentDefinitions(array($paymentDefinition));
    $plan->setMerchantPreferences($merchantPreferences);

    try {
      $id = $plan->create(get_api_context())->getId();
      $output = '<a href="/get-plan/' . $id . '">Ver los detalles del pan creado</a>';
      return $output;

    } catch (Exception $ex) {
      throw $ex;
    }

  }
}

function sample_create_billing_agreement() {

}

/**
 * @param $id
 * @return mixed
 * @throws Exception
 */
function sample_get_plan($id) {
  _paypal_get_sdk();

  try {
    $plan = paypal_sdk_get_plan($id);
    return '<pre>' . print_r($plan, TRUE) . '</pre>';
  } catch (Exception $ex) {
    throw $ex;
  }

}

/**
 * @param $id
 * @return mixed
 * @throws Exception
 */
function sample_activate_plan($id) {
  _paypal_get_sdk();

  try {
    $activatePlanRequest = paypal_sdk_activate_plan_request();
    $createdPlan = paypal_sdk_get_plan($id);
    $createdPlan->update($activatePlanRequest, get_api_context());

    // now we have an activatd plan. We need request it again? // @todo really we need this?
    $plan = paypal_sdk_get_plan($createdPlan->getId(), get_api_context());
    return '<pre>' . print_r($plan, TRUE) . '</pre>';

  } catch (Exception $ex) {
    throw $ex;
  }

}


// Helpers
// --------------------------------------
/**
 * Implementation of hook_theme.
 */
function paypal_billing_admin_theme() {
  return array(
    'tableform' => array(
      'render element' => 'form',
    ),
  );
}


/**
 * Theme callback for the form table.
 */
function theme_tableform(&$variables) {
  // Get the userful values.
  $form = $variables['form'];
  $rows = $form['rows'];
  $header = $form['#header'];

  // Setup the structure to be rendered and returned.
  $content = array(
    '#theme' => 'table',
    '#header' => $header,
    '#rows' => array(),
  );

  // Traverse each row.  @see element_chidren().
  foreach (element_children($rows) as $row_index) {
    $row = array();
    // Traverse each column in the row.  @see element_children().
    foreach (element_children($rows[$row_index]) as $col_index) {
      // Render the column form element.
      $row[] = drupal_render($rows[$row_index][$col_index]);
    }
    // Add the row to the table.
    $content['#rows'][] = $row;
  }

  // Redner the table and return.
  return drupal_render($content);
}